### ISSUE TITLE
Prometheus async worker thread crashes after upgrade

### ISSUE THREAD

**Issue by sbussetti** [jenkinsci/prometheus-plugin#128]
### Steps to reproduce

Upgraded jenkins with previously working prometheus metrics plugin.
Using the official Jenkins docker image / alpine.  Upgraded jenkins core from 2.176.2 to 2.176.3, upgraded prometheus plugin from 2.0.0 to 2.0.6

On startup, and continuing periodically after, I see the following stack trace in my logs:
```

Sep 18, 2019 5:11:26 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Started prometheus_async_worker
Sep 18, 2019 5:11:26 PM hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
SEVERE: A thread (prometheus_async_worker thread/194) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.StackOverflowError
        at java.util.TreeMap.put(TreeMap.java:568)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:44)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
        at org.jenkinsci.plugins.prometheus.util.FlowNodes.traverseTree(FlowNodes.java:49)
...
```

**Comment by sbussetti** [comment]
As I am sure you'd assume, disabling all job-related metrics via the config skips the code and therefore makes the metrics endpoint work again.

**Comment by markyjackson-taulia** [comment]
I never assume anything 😉

**Comment by ssrivastava-papajohns** [comment]
@markyjackson-taulia Facing the same issue. let me know if there is any fix. Thanks

Jenkins(2.194)
Prometheus(2.0.6)

**Comment by kisoku** [comment]
I just ran into the same issue on Jenkins 2.199 and Prometheus 2.0.6. Was forced to downgrade the plugin to 2.0.0 as I would wind up with one cpu pegged and jenkins would no longer service requests

**Comment by ssrivastava-papajohns** [comment]
@sbussetti @kisoku @markyjackson-taulia  Is this issue gone?

**Comment by sbussetti** [comment]
@ssrivastava-papajohns I'll update and re-enable the problem stats this week and let you know.

**Comment by ssrivastava-papajohns** [comment]
@sbussetti Thanks for your response. This issue is a blocker for me for the last 1 month. Hoping for the fix.

FYI, I have an observation that If I select only failed Jobs

![image](https://user-images.githubusercontent.com/50203726/67378999-c5e46780-f5a5-11e9-91bd-fb0de6169a16.png)
 
I get the following job metrics on https://[Jenkins-Host]/prometheus:

default_jenkins_builds_duration_milliseconds_summary_count
default_jenkins_builds_duration_milliseconds_summary_sum
default_jenkins_builds_failed_build_count
default_jenkins_builds_last_build_result_ordinal
default_jenkins_builds_last_build_result
default_jenkins_builds_last_build_duration_milliseconds
default_jenkins_builds_stage_duration_milliseconds_summary_count
default_jenkins_builds_stage_duration_milliseconds_summary_sum

But if I select successful jobs either with or without the failed job checked,

![image](https://user-images.githubusercontent.com/50203726/67379697-de08b680-f5a6-11e9-9b9b-73cacd8f7293.png)
 

I get a blank page on https://[Jenkins-Host]/prometheus and the same error on stack trace that @sbussetti mentioned in this issue.


PS: I have around 1000 Jobs on my Jenkins. and Jenkins is hosted on the GCP Kubernetes cluster.

Also, I have another Jenkins with a similar configuration with somewhere around 50 Jobs in it. I am able to get successful as well failed job metric there. 


Notify: 

@markyjackson-taulia

**Comment by sbussetti** [comment]
As of today I am running prom plugin 2.0.6 and jenkins 2.176.3 with all metrics enabled  (see screenshot) and things, so far, seem stable.

![image](https://user-images.githubusercontent.com/913361/67404812-e5699900-f581-11e9-819f-c5c94888243c.png)

**Comment by markyjackson-taulia** [comment]
Can you also show what you prometheus.yaml looks like?

**Comment by ssrivastava-papajohns** [comment]
@markyjackson-taulia Thanks Marky for your response below is my prometheus.yml

prometheus.yml
-------------------------------------------
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:

## A scrape configuration containing exactly one endpoint to scrape:
## Here it's Prometheus itself.
scrape_configs:
  ## The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'jenkins_job'
    metrics_path: '/prometheus'
    bearer_token: '1234567nxbhirn63454739374645'
    static_configs:
     - targets: ['3x.xx0.xx.x:80']

**Comment by ssrivastava-papajohns** [comment]
Hi, @markyjackson-taulia @sbussetti Is there any update on this issue?

**Comment by cpitstick-argo** [comment]
Argo AI uses Jenkins and we're seeing this as well.

Additionally, it looks like there are duplicates of this issue
- https://github.com/jenkinsci/prometheus-plugin/issues/134
- https://github.com/jenkinsci/prometheus-plugin/issues/127

@markyjackson-taulia @sbussetti -- I'd like to see what we can do to get this issue resolved and I'm happy to help on behalf of Argo AI.

**Comment by cpitstick-argo** [comment]
My first guess here is that the issue here is that the traversal of the FlowNodes is using a recursive algorithm. By moving it to an iterative algorithm (which is hard to derive from first principles but fortunately we have Google), my guess is one of two things will happen:

1. The traversal runs out of stack space simply because companies with larger Jenkins deployments have more FlowNodes than there is stack memory, and moving it to iterative moves the memory to the heap instead of the call stack, which will completely resolve the issue.

2. The plugin will go into a truly infinite recursion, at which point we can then figure out why this is happening. Given that FlowNodes are a Jenkins construct and not one of this plugin, I'd be surprised if the tree is constructed badly.

I concede I don't know exactly what FlowNodes or why this broke from 2.0.0 -> 2.0.6, but that's my first guess.

**Comment by cpitstick-argo** [comment]
We've also submitted a Jenkins bug on this as well: https://issues.jenkins-ci.org/browse/JENKINS-59966

**Comment by ssrivastava-papajohns** [comment]
Hi @cpitstick-argo  I can't see any activity on JENKINS-59966. Is there any you have on this issue?

**Comment by cpitstick-argo** [comment]
@ssrivastava-papajohns We're waiting just like you are...

**Comment by cpitstick-argo** [comment]
@ssrivastava-papajohns Should we try our own hand at fixing this ourselves? Maybe we should collaborate here...

**Comment by cpitstick-argo** [comment]
After testing here at Argo, we believe this fixes the issue: https://github.com/jenkinsci/prometheus-plugin/pull/143

Note that in order for the fix to be built into a new JAR, https://github.com/jenkinsci/prometheus-plugin/pull/142 is also required.

**Comment by intelmatt** [comment]
Any idea when the fix will be released in a new version of the plugin?

**Comment by markyjackson-taulia** [comment]
Over the weekend and into most of yesterday there was an infra problem that put the breaks on most work. I will pick it up in the next few days

**Comment by markyjackson-taulia** [comment]
This has been addressed
