### ISSUE TITLE
2.0.6 Worker fails to load

### ISSUE THREAD

**Issue by jniebuhr** [jenkinsci/prometheus-plugin#137]
### Steps to reproduce
How can we reproduce the issue
1. Install Jenkins 2.190.2
2. Install Prometheus plugin 2.0.6
3. Observe startup logs

### Expected behaviour
Worker should start and there should be logs at the /prometheus endpoint.

### Actual behaviour
The worker seems to fail to load on Jenkins startup with the following error:

```
2019-11-19 15:12:33.769+0000 [id=25]	WARNING	h.ExtensionFinder$GuiceFinder$FaultTolerantScope$1#error: Failed to instantiate Key[type=org.jenkinsci.plugins.prometheus.service.PrometheusAsyncWorker, annotation=[none]]; skipping this component
java.lang.IllegalArgumentException: Collector already registered that provides name: default_jenkins_up
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54)
	at org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics.<init>(DefaultPrometheusMetrics.java:27)
	at org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics$$FastClassByGuice$$af5295cb.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:567)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:84)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:567)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Caused: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Collector already registered that provides name: default_jenkins_up
  at org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics.<init>(DefaultPrometheusMetrics.java:24)
  while locating org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics
  at org.jenkinsci.plugins.prometheus.context.Context.configure(Context.java:13)
  while locating org.jenkinsci.plugins.prometheus.service.PrometheusMetrics
    for parameter 0 at org.jenkinsci.plugins.prometheus.service.PrometheusAsyncWorker.setPrometheusMetrics(PrometheusAsyncWorker.java:26)

1 error
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:439)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:401)
	at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:392)
	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:344)
	at hudson.ExtensionList.load(ExtensionList.java:381)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
	at hudson.ExtensionList.iterator(ExtensionList.java:172)
	at hudson.ExtensionList.get(ExtensionList.java:149)
	at jenkins.metrics.api.Metrics$HealthCheckMetricsProvider.getMetricSet(Metrics.java:359)
	at jenkins.metrics.api.MetricProviderListener.onChange(MetricProviderListener.java:91)
	at jenkins.metrics.api.MetricProviderListener.attach(MetricProviderListener.java:77)
	at jenkins.metrics.api.Metrics.afterExtensionsAugmented(Metrics.java:313)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The /prometheus endpoint then seems to work and I can also move it to another endpoint but it'll never display any metrics.

### Server configuration

**Operating system**: Ubuntu 18.04 Bionic Beaver

**Jenkins Version**: 2.190.2

**Plugin Version**: 2.0.6

### Notify

@markyjackson-taulia

**Comment by ababushk** [comment]
Same issue on Jenkins 2.190.3 and Prometheus plugin 2.0.6, no info at /prometheus endpoint at all

**Comment by markyjackson-taulia** [comment]
@jniebuhr @ababushk I cannot reproduce this

**Comment by ababushk** [comment]
@markyjackson-taulia thank you for looking into this!
I've just reproduced the issue on my local Jenkins 2.204.1 instance. However, I didn't notice that I used backup data from production instance (which survived many updates and plugins installations). I did this in my $JENKINS_HOME:
```
find . | grep prometheus | xargs rm -rf {}
```
And after Jenkins restart plugin started normally and I can see data on /prometheus endpoint.

Before that 2.0.0 version was installed. May be there is some upgrade issue? Please let me know if I can gather additional data.

**Comment by markyjackson-taulia** [comment]
@ababushk Let me run through the upgrade path to see if I can reproduce that angle. I will get to that in the next few days

**Comment by hedchain** [comment]
@markyjackson-taulia Same issue on jenkins 2.164.3

`5:55:20 PM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate Key[type=org.jenkinsci.plugins.prometheus.service.PrometheusAsyncWorker, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Collector already registered that provides name: default_jenkins_up
  at org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics.<init>(DefaultPrometheusMetrics.java:24)
  while locating org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics
  at org.jenkinsci.plugins.prometheus.context.Context.configure(Context.java:13)
  while locating org.jenkinsci.plugins.prometheus.service.PrometheusMetrics
    for parameter 0 at org.jenkinsci.plugins.prometheus.service.PrometheusAsyncWorker.setPrometheusMetrics(PrometheusAsyncWorker.java:26)`

**Comment by JaminenB** [comment]
We also had this issue and resolved it by upgrading the **Permissive Script Security** plugin from v0.5 to v0.6 based on the following links: 

[JENKINS-59145](https://issues.jenkins-ci.org/browse/JENKINS-59145) - We also started experiencing this pipeline blank page issue but not system-wide.
[Permissive Script Security PR](https://github.com/jenkinsci/permissive-script-security-plugin/pull/4)

- Note that the problem cluster was running v0.5 of the **Permissive Script Security** plugin and v2.0.6 of the Prometheus plugin, which created the blank page issue.  
- Our other clusters are working as expected and are running v0.3 of the Permissive Script Security plugin and v2.0.6 of the Prometheus plugin. 

The issue could be with versions v0.4-v0.5 of the Permissive Script Security plugin. Try upgrading to v0.6 if you're experiencing the blank page issue on the /prometheus/ endpoint.

**Comment by markyjackson-taulia** [comment]
Please update to the latest 2.0.7 version as well as update Permissive Script Security
