### ISSUE TITLE
Skip errors on a single job and continue to collect metrics on other jobs

### ISSUE THREAD

**Issue by sburky32** [jenkinsci/prometheus-plugin#206]
### Steps to reproduce
How can we reproduce the issue
1. go into one of builds and remove a build.xml or clover.xml file
ie rm /localhome/jenkins/jobs/somejob/branches/branch/builds/1/*.xml

### Expected behaviour
Should print an error about the file not being there, but it should continue to collect metrics on other jobs.

### Actual behaviour
It gets a file not found exception and stops collecting metrics on other jobs

### Server configuration

**Operating system**:
RH 7.9

**Jenkins Version**:
jenkins-2.263.3-1.1

**Plugin Version**:
2.0.8

### Notify

@markyjackson-taulia

**Comment by sburky32** [comment]
```
java.io.FileNotFoundException: [pathtoFile] (No such file or direc
tory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at hudson.plugins.clover.CloverCoverageParser.parse(CloverCoverageParser.java:51)
        at hudson.plugins.clover.CloverBuildAction.computeResult(CloverBuildAction.java:201)
        at hudson.plugins.clover.CloverBuildAction.access$000(CloverBuildAction.java:40)
        at hudson.plugins.clover.CloverBuildAction$1.load(CloverBuildAction.java:51)
        at hudson.plugins.clover.CloverBuildAction$1.load(CloverBuildAction.java:48)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
Caused: java.util.concurrent.ExecutionException
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:289)
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:276)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:111)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:132)
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2381)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2351)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3969)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4829)
        at hudson.plugins.clover.CloverBuildAction.getResult(CloverBuildAction.java:192)
        at hudson.plugins.clover.CloverBuildAction.getBuildHealth(CloverBuildAction.java:68)
        at hudson.model.Job.getBuildHealthReports(Job.java:1209)
        at hudson.model.Job.getBuildHealth(Job.java:1183)
        at org.jenkinsci.plugins.prometheus.JobCollector.appendJobMetrics(JobCollector.java:286)
        at org.jenkinsci.plugins.prometheus.JobCollector.lambda$collect$0(JobCollector.java:220)
        at org.jenkinsci.plugins.prometheus.util.Jobs.forEachJob(Jobs.java:14)
        at org.jenkinsci.plugins.prometheus.JobCollector.collect(JobCollector.java:214)
```

looks like `job.getBuildHealth().getScore();` can change what files it is looking for based on plugins installed to jenkins.  If the build is older than the plugins that contribute to the score, the files might not exist.
