### ISSUE TITLE
Plugin broken in latest jenkins LTS (2.277.1)

### ISSUE THREAD

**Issue by circa10a** [jenkinsci/prometheus-plugin#237]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.277.1
OS: Linux - 4.4.0-1117-aws
---
windows-slaves:1.6
credentials:2.3.15
command-launcher:1.5
jdk-tool:1.5
mailer:1.32.1
display-url-api:2.3.4
structs:1.22
docker-workflow:1.26
git-server:1.9
pipeline-model-definition:1.8.4
workflow-cps-global-lib:2.18
antisamy-markup-formatter:2.1
extended-read-permission:3.2
pipeline-stage-tags-metadata:1.8.4
cloudbees-folder:6.15
maven-plugin:3.10
pipeline-utility-steps:2.6.1
authentication-tokens:1.4
blueocean-autofavorite:1.2.4
popper-api:1.16.1-2
splunk-devops:1.9.6
javadoc:1.6
run-condition:1.5
parameterized-trigger:2.40
splunk-devops-extend:1.9.6
blueocean-dashboard:1.24.5
favorite:2.3.3
workflow-step-api:2.23
mercurial:2.10
handy-uri-templates-2-api:2.1.8-1.0
lockable-resources:2.10
pipeline-model-api:1.8.4
jquery:1.12.4-1
throttle-concurrents:2.0.3
font-awesome-api:5.15.2-2
blueocean-display-url:2.4.1
plugin-util-api:2.0.0
token-macro:2.15
workflow-aggregator:2.6
blueocean-pipeline-editor:1.24.5
handlebars:1.1.1
pipeline-build-step:2.13
variant:1.4
build-timeout:1.20
blueocean-github-pipeline:1.24.5
script-security:1.76
blueocean-personalization:1.24.5
htmlpublisher:1.25
blueocean-config:1.24.5
blueocean-commons:1.24.5
ssh-credentials:1.18.1
credentials-binding:1.24
workflow-basic-steps:2.23
scm-api:2.6.4
readonly-parameters:1.0.0
workflow-job:2.40
workflow-cps:2.90
configuration-as-code:1.47
jenkins-design-language:1.24.5
jackson2-api:2.12.1
bouncycastle-api:2.20
github-api:1.123
echarts-api:5.0.1-1
jquery-detached:1.2.1
ace-editor:1.1
github:1.33.1
git-client:3.7.0
jjwt-api:0.11.2-9.c8b45b8bb173
ldap:2.4
blueocean-events:1.24.5
branch-api:2.6.3
okhttp-api:3.14.9
pubsub-light:1.13
matrix-auth:2.6.6
momentjs:1.1.1
blueocean-web:1.24.5
pipeline-rest-api:2.19
pipeline-milestone-step:1.3.2
durable-task:1.35
golang:1.4
github-branch-source:2.10.2
workflow-support:3.8
blueocean-i18n:1.24.5
role-strategy:3.1.1
workflow-multibranch:2.22
build-pipeline-plugin:1.5.8
pipeline-input-step:2.12
git:4.7.0
workflow-durable-task-step:2.38
blueocean-core-js:1.24.5
blueocean-pipeline-api-impl:1.24.5
blueocean-git-pipeline:1.24.5
mask-passwords:3.0
docker-commons:1.17
bootstrap4-api:4.6.0-2
checks-api:1.6.1
pipeline-stage-step:2.5
jira:3.1.1
blueocean-jwt:1.24.5
junit:1.49
workflow-scm-step:2.12
blueocean-bitbucket-pipeline:1.24.5
plain-credentials:1.7
blueocean-rest-impl:1.24.5
blueocean-rest:1.24.5
trilead-api:1.0.13
blueocean:1.24.5
terraform:1.0.10
workflow-api:2.42
conditional-buildstep:1.4.1
plugin-usage-plugin:1.2
ssh-agent:1.21
hidden-parameter:0.0.4
pipeline-graph-analysis:1.10
jquery3-api:3.5.1-3
matrix-project:1.18
blueocean-jira:1.24.5
snakeyaml-api:1.27.0
pipeline-stage-view:2.19
jsch:0.1.55.2
metrics:4.0.2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
jaxb:2.3.0.1
pipeline-model-extensions:1.8.4
blueocean-pipeline-scm-api:1.24.5
sse-gateway:1.24
cloudbees-disk-usage-simple:0.10
vagrant:1.0.2
prometheus:2.0.9
cloudbees-bitbucket-branch-source:2.9.7
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

no agents, just master

```
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

### Reproduction steps

1. Upgrade to Jenkins 2.277.1
2. Install prometheus plugin 2.0.7 or 2.0.8 or 2.0.9

### Results

Expected result:

Expected metrics at `/prometheus`

Actual result:

Empty response, but a 200 response code

```
< HTTP/1.1 200 OK
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/plain; version=0.0.4; charset=utf-8
```

Stack trace:

```
	at java.lang.Thread.run(Thread.java:748)
2021-03-26 00:31:12.268+0000 [id=89]	INFO	o.j.p.prometheus.JobCollector#lambda$collect$0: Collecting metrics for job [sample_job_name]
2021-03-26 00:31:12.312+0000 [id=89]	WARNING	hudson.FilePath#_getChannelForSerialization: A FilePath object is being serialized when it should not be, indicating a bug in a plugin. See https://jenkins.io/redirect/filepath-serialization for details.
java.io.NotSerializableException: The calling thread Thread[prometheus_async_worker thread,5,main] has no associated channel. The current object null is interface org.jenkinsci.remoting.SerializableOnlyOverRemoting, but it is likely being serialized/deserialized without the channel
	at org.jenkinsci.remoting.SerializableOnlyOverRemoting.getChannelForSerialization(SerializableOnlyOverRemoting.java:67)
	at hudson.FilePath._getChannelForSerialization(FilePath.java:3265)
	at hudson.FilePath.readObject(FilePath.java:3273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.thoughtworks.xstream.core.util.SerializationMembers.callReadObject(SerializationMembers.java:132)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doUnmarshal(SerializableConverter.java:443)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
	at hudson.util.RobustMapConverter.read(RobustMapConverter.java:58)
	at hudson.util.RobustMapConverter.putCurrentEntryIntoMap(RobustMapConverter.java:49)
	at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:98)
	at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:92)
	at com.thoughtworks.xstream.converters.collections.MapConverter.unmarshal(MapConverter.java:87)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:439)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:341)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:280)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:117)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readCompleteItem(AbstractCollectionConverter.java:147)
	at com.thoughtworks.xstream.converters.collections.ArrayConverter.unmarshal(ArrayConverter.java:54)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:439)
	at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:341)
	at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:280)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1409)
	at hudson.util.XStream2.unmarshal(XStream2.java:161)
	at hudson.util.XStream2.unmarshal(XStream2.java:132)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1388)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1282)
	at hudson.XmlFile.read(XmlFile.java:149)
	at org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage.load(SimpleXStreamFlowNodeStorage.java:204)
	at org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage.access$000(SimpleXStreamFlowNodeStorage.java:71)
	at org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage$1.load(SimpleXStreamFlowNodeStorage.java:76)
	at org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage$1.load(SimpleXStreamFlowNodeStorage.java:74)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3969)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4829)
	at org.jenkinsci.plugins.workflow.support.storage.SimpleXStreamFlowNodeStorage.getNode(SimpleXStreamFlowNodeStorage.java:101)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$TimingFlowNodeStorage.getNode(CpsFlowExecution.java:1813)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.getNode(CpsFlowExecution.java:1191)
	at org.jenkinsci.plugins.workflow.graph.FlowNode.loadParents(FlowNode.java:165)
	at org.jenkinsci.plugins.workflow.graph.FlowNode.getParents(FlowNode.java:156)
	at org.jenkinsci.plugins.workflow.graphanalysis.ForkScanner.next(ForkScanner.java:573)
	at org.jenkinsci.plugins.workflow.graphanalysis.AbstractFlowScanner.next(AbstractFlowScanner.java:211)
	at org.jenkinsci.plugins.workflow.graphanalysis.ForkScanner.next(ForkScanner.java:563)
	at org.jenkinsci.plugins.workflow.graphanalysis.ForkScanner.visitSimpleChunks(ForkScanner.java:766)
	at org.jenkinsci.plugins.workflow.graphanalysis.ForkScanner.visitSimpleChunks(ForkScanner.java:631)
	at org.jenkinsci.plugins.prometheus.util.FlowNodes.getSortedStageNodes(FlowNodes.java:26)
	at org.jenkinsci.plugins.prometheus.JobCollector.appendJobMetrics(JobCollector.java:360)
	at org.jenkinsci.plugins.prometheus.JobCollector.lambda$collect$0(JobCollector.java:220)
	at org.jenkinsci.plugins.prometheus.util.Jobs.forEachJob(Jobs.java:14)
	at org.jenkinsci.plugins.prometheus.JobCollector.collect(JobCollector.java:214)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:223)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:144)
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics.collectMetrics(DefaultPrometheusMetrics.java:51)
	at org.jenkinsci.plugins.prometheus.service.PrometheusAsyncWorker.execute(PrometheusAsyncWorker.java:41)
	at hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:100)
	at java.lang.Thread.run(Thread.java:748)
2021-03-26 00:31:12.330+0000 [id=89]	SEVERE	h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (prometheus_async_worker thread/89) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NullPointerException
	at org.jenkinsci.plugins.prometheus.JobCollector.lambda$appendJobMetrics$1(JobCollector.java:310)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.jenkinsci.plugins.prometheus.JobCollector.appendJobMetrics(JobCollector.java:310)
	at org.jenkinsci.plugins.prometheus.JobCollector.lambda$collect$0(JobCollector.java:220)
	at org.jenkinsci.plugins.prometheus.util.Jobs.forEachJob(Jobs.java:14)
	at org.jenkinsci.plugins.prometheus.JobCollector.collect(JobCollector.java:214)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:190)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:223)
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:144)
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)
	at org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics.collectMetrics(DefaultPrometheusMetrics.java:51)
	at org.jenkinsci.plugins.prometheus.service.PrometheusAsyncWorker.execute(PrometheusAsyncWorker.java:41)
	at hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:100)
	at java.lang.Thread.run(Thread.java:748)

**Comment by circa10a** [comment]
After waiting a while. 2.0.9 populated
