### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mabushey** [jenkinsci/prometheus-plugin#27]
I installed the 1.1.1 version of  Prometheus metrics plugin in Jenkins and restarted. It doesn't work though:
```
curl -I https://myjenkins.com/prometheus
HTTP/1.1 302 Found
...
```

**Comment by perrefe** [comment]
Same situation here using http schema.

**Comment by clemSeveillac** [comment]
What about adding a slash after `prometheus` like the HTTP 302 Location header suggest?

(note we still have issues then, getting an empty HTTP 200 then, cf. https://github.com/jenkinsci/prometheus-plugin/issues/30)

**Comment by ezyang** [comment]
Same here:

```
MacBook-Pro-97:ossci-infra ezyang$ curl https://ci.pytorch.org/jenkins/prometheus/ -I
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Thu, 08 Mar 2018 08:43:57 GMT
Content-Type: text/plain; version=0.0.4; charset=utf-8
Connection: keep-alive
X-Content-Type-Options: nosniff
Set-Cookie: JSESSIONID.c15e7c65=node0ejpoi0mdp5w1pkx6osrrg3z11245.node0;Path=/jenkins;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Strict-Transport-Security: max-age=15768000

MacBook-Pro-97:ossci-infra ezyang$ curl https://ci.pytorch.org/jenkins/prometheus/ -v
*   Trying 34.201.149.161...
* TCP_NODELAY set
* Connected to ci.pytorch.org (34.201.149.161) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=ci.pytorch.org
*  start date: Jan 17 16:22:47 2018 GMT
*  expire date: Apr 17 16:22:47 2018 GMT
*  subjectAltName: host "ci.pytorch.org" matched cert's "ci.pytorch.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET /jenkins/prometheus/ HTTP/1.1
> Host: ci.pytorch.org
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.10.3 (Ubuntu)
< Date: Thu, 08 Mar 2018 08:44:16 GMT
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< Set-Cookie: JSESSIONID.c15e7c65=node0132o9usjjdsgi1wpdjrmpklu9j1252.node0;Path=/jenkins;Secure;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Strict-Transport-Security: max-age=15768000
< 
* Connection #0 to host ci.pytorch.org left intact
```

**Comment by externl** [comment]
I'm also experiencing this. Just an empty page at `/prometheus/`. Anyone know how to get this working?

**Comment by jasooonko** [comment]
I'm hitting the same issue. I noticed that whenever we hit `/prometheus` endpoint, the thread dump shows that the thread is locked and never released.

```
Handling GET /prometheus/ from x.x.x.x : RequestHandlerThread[#1] id=22 state=RUNNABLE
    at sun.nio.fs.UnixNativeDispatcher.open0(Native Method)
    at sun.nio.fs.UnixNativeDispatcher.open(UnixNativeDispatcher.java:71)
    at sun.nio.fs.UnixChannelFactory.open(UnixChannelFactory.java:257)
    at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:136)
    at sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:148)
    at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:212)
    at java.nio.file.Files.newByteChannel(Files.java:361)
    at java.nio.file.Files.newByteChannel(Files.java:407)
    at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
    at java.nio.file.Files.newInputStream(Files.java:152)
    at hudson.XmlFile.read(XmlFile.java:142)
...
    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@7e990ed7
```

**Comment by mmuth** [comment]
We have more or less the same issue here. I just tried to find something out: 

I noticed that when I restart Jenkins and load the Prometheus endpoint the very first request needs very long (and the Thread dump looks similar to yours, @jasooonko )... but if I wait long enough, the metrics will show up and seem to be stable from then on.

At first, I initially loaded the endpoint twice, after the first request seem to need so long. I was just not patient - and if I do this, nothing won't appear anymore. Then i only get the empty response forever, like you.

Well in a regular environment, where Prometheus scrapes regularly in a short interval, it might be similar to my initial fail when loading and loading again... so I have not found any solution yet, but I'd like to share my observation with you...

**Comment by markyjackson-taulia** [comment]
This shouldn't be an issue any longer. I have tested all new versions successfully.

**Comment by kunal-kannav** [comment]
I am still facing the issue, plugin is installed successfully.
When I try to load the endpoint, a blank screen pops up

**Comment by markyjackson-taulia** [comment]
@kunal-kannav can you provide your config and screen shots
