### ISSUE TITLE
prometheus_async_worker in deadlock with flyweight executor creating new build

### ISSUE THREAD

**Issue by tzhu-yelp** [jenkinsci/prometheus-plugin#717]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.462.3
OS: Linux - 5.15.0-1071-aws
Java: 17.0.13 - Amazon.com Inc. (OpenJDK 64-Bit Server VM)
---
analysis-model-api:12.9.0
ansicolor:1.0.5
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.4-118.v199115451c4d
asm-api:9.7.1-97.v4cc844130d97
authentication-tokens:1.119.v50285141b_7e1
aws-credentials:231.v08a_59f17d742
aws-java-sdk:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-api-gateway:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-autoscaling:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-cloudformation:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-cloudfront:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-codebuild:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-codedeploy:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-ec2:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-ecr:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-ecs:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-efs:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-elasticbeanstalk:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-elasticloadbalancingv2:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-iam:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-kinesis:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-lambda:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-logs:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-minimal:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-organizations:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-secretsmanager:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-sns:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-sqs:1.12.772-474.v7f79a_2046a_fb_
aws-java-sdk-ssm:1.12.772-474.v7f79a_2046a_fb_
badge:2.2
blueocean:1.27.16
blueocean-bitbucket-pipeline:1.27.16
blueocean-commons:1.27.16
blueocean-config:1.27.16
blueocean-core-js:1.27.16
blueocean-dashboard:1.27.16
blueocean-display-url:2.4.3
blueocean-events:1.27.16
blueocean-git-pipeline:1.27.16
blueocean-github-pipeline:1.27.16
blueocean-i18n:1.27.16
blueocean-jwt:1.27.16
blueocean-personalization:1.27.16
blueocean-pipeline-api-impl:1.27.16
blueocean-pipeline-editor:1.27.16
blueocean-pipeline-scm-api:1.27.16
blueocean-rest:1.27.16
blueocean-rest-impl:1.27.16
blueocean-web:1.27.16
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1178.v969d9eb_c728e
build-failure-analyzer:2.27.0
build-user-vars-plugin:176.vb_9c7907fd524
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.1
cloudbees-bitbucket-branch-source:888.v8e6d479a_1730
cloudbees-disk-usage-simple:205.v47f4ee8803d1
cloudbees-folder:6.955.v81e2a_35c08d3
command-launcher:107.v773860566e2e
commons-compress-api:1.26.1-2
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
config-file-provider:978.v8e85886ffdc4
configuration-as-code:1850.va_a_8c31d3158b_
copyartifact:749.vfb_dca_a_9b_6549
credentials:1384.vf0a_2ed06f9c6
credentials-binding:681.vf91669a_32e45
data-tables-api:2.1.8-1
description-setter:239.vd0a_6b_785f92d
display-url-api:2.204.vf6fddd8a_8b_e9
docker-commons:443.v921729d5611d
docker-custom-build-environment:1.7.3
docker-workflow:580.vc0c340686b_54
downstream-build-cache:1.7
durable-task:577.v2a_8a_4b_7c0247
ec2-fleet:2.7.1
echarts-api:5.5.1-3
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1844.v3ea_a_b_842374a_
extended-read-permission:53.v6499940139e5
favorite:2.221.v19ca_666b_62f5
font-awesome-api:6.6.0-2
forensics-api:2.6.0
generic-webhook-trigger:2.2.5
git:5.5.2
git-client:5.0.0
github:1.40.0
github-api:1.321-468.v6a_9f5f2d5a_7e
github-branch-source:1803.v98e3d8a_c8169
greenballs:1.15.1
gson-api:2.11.0-85.v1f4e87273c33
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.36
instance-identity:201.vd2a_b_5a_468a_a_6
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:280.v050b_5c849f69
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jenkins-design-language:1.27.16
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
jobConfigHistory:1277.vb_9a_0808495d7
joda-time-api:2.13.0-93.v9934da_29b_a_e9
jqs-monitoring:37.vf50a_82a_0b_f32
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-101.v7a_8666713110
json-path-api:2.9.0-118.v7f23ed82a_8b_8
junit:1307.vdd5b_2646279e
kubernetes:4219.v40ff98cfb_d6f
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:190.v03c305394deb_
lockable-resources:1320.v1f0dff578476
mailer:488.v0c9639c1a_eb_3
matrix-auth:3.2.2
matrix-project:839.vff91cd7e3a_b_2
maven-plugin:3.23
metrics:4.2.21-451.vd51df8df52ec
mina-sshd-api-common:2.14.0-133.vcc091215a_358
mina-sshd-api-core:2.14.0-133.vcc091215a_358
monitoring:1.99.0
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
opentelemetry:3.1391.vcb_a_a_b_9779d75
opentelemetry-api:1.40.0-36.v1e02b_b_4db_8f4
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-graph-view:313.v1322ce83d680
pipeline-groovy-lib:740.va_2701257fe8d
pipeline-input-step:495.ve9c153f6067b_
pipeline-maven:1457.vf7a_de13b_c0d4
pipeline-maven-api:1457.vf7a_de13b_c0d4
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-definition:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-extensions:2.2214.vb_b_34b_2ea_9b_83
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2214.vb_b_34b_2ea_9b_83
pipeline-stage-view:2.34
pipeline-utility-steps:2.18.0
plain-credentials:183.va_de8f1dd5a_2b_
plugin-util-api:5.1.0
prism-api:1.29.0-17
prometheus:787.v52e8f47488fc
pubsub-light:1.18
readonly-parameters:1.0.0
rebuild:332.va_1ee476d8f6d
saml:4.464.vea_cb_75d7f5e0
scm-api:696.v778d637b_a_762
scoring-load-balancer:136.veda_e0c5137c1
script-security:1365.v4778ca_84b_de5
simple-theme-plugin:196.v96d9592f4efa_
snakeyaml-api:2.3-123.v13484c65210a_
sse-gateway:1.27
ssh-agent:376.v8933585c69d3
ssh-credentials:343.v884f71d78167
ssh-slaves:2.973.v0fa_8c0dea_f9f
sshd:3.330.vc866a_8389b_58
structs:338.v848422169819
throttle-concurrents:2.14
timestamper:1.27
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
update-sites-manager:2.0.0
variant:60.v7290fc0eb_b_cd
warnings-ng:11.10.0
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3975.v567e2a_1ffa_22
workflow-durable-task-step:1371.vb_7cec8f3b_95e
workflow-job:1436.vfa_244484591f
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:930.vf51d22b_ce488
yelp-jenkins-plugin:0.17.3
yet-another-build-visualizer:1.17
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller: Ubuntu 24.04 in Kubernetes
Agents: not involved in the problem

### Reproduction steps

Don't have reproduction steps, only a thread dump

### Expected Results

Builds complete and do not deadlock with prometheus_async_worker

### Actual Results

Builds on this controller were reported to not be making progress for several hours. JavaMelody reported there was a potential thread deadlock, and a thread dump provided the following:

```
    "Executor #-1 for Built-In Node" Id=138915 Group=main BLOCKED on jenkins.model.lazy.LazyLoadRunMapEntrySet@1bcc66c7 owned by "prometheus_async_worker thread" Id=138789
    	at jenkins.model.lazy.LazyLoadRunMapEntrySet.clearCache(LazyLoadRunMapEntrySet.java:37)
    	-  blocked on jenkins.model.lazy.LazyLoadRunMapEntrySet@1bcc66c7
    	at jenkins.model.lazy.AbstractLazyLoadRunMap.put(AbstractLazyLoadRunMap.java:625)
    	-  locked hudson.model.RunMap@3f263d52
    	at jenkins.model.lazy.AbstractLazyLoadRunMap._put(AbstractLazyLoadRunMap.java:606)
    	at hudson.model.RunMap.put(RunMap.java:227)
    	at jenkins.model.lazy.LazyBuildMixIn.newBuild(LazyBuildMixIn.java:192)
    	-  locked org.jenkinsci.plugins.workflow.job.WorkflowJob$1@149939d4
    	at jenkins.model.ParameterizedJobMixIn$ParameterizedJob.createExecutable(ParameterizedJobMixIn.java:507)
    	at jenkins.model.ParameterizedJobMixIn$ParameterizedJob.createExecutable(ParameterizedJobMixIn.java:325)
    	at hudson.model.Executor$1.call(Executor.java:374)
    	at hudson.model.Executor$1.call(Executor.java:354)
    	at hudson.model.Queue._withLock(Queue.java:1470)
    	at hudson.model.Queue.withLock(Queue.java:1326)
    	at hudson.model.Executor.run(Executor.java:354)
    
    	Number of locked synchronizers = 1
    	- java.util.concurrent.locks.ReentrantLock$NonfairSync@323aed2d
```
and
```
    "prometheus_async_worker thread" Id=138789 Group=main BLOCKED on hudson.model.RunMap@3f263d52 owned by "Executor #-1 for Built-In Node" Id=138915
    	at jenkins.model.lazy.AbstractLazyLoadRunMap.all(AbstractLazyLoadRunMap.java:655)
    	-  blocked on hudson.model.RunMap@3f263d52
    	at jenkins.model.lazy.LazyLoadRunMapEntrySet.all(LazyLoadRunMapEntrySet.java:32)
    	-  locked jenkins.model.lazy.LazyLoadRunMapEntrySet@1bcc66c7
    	at jenkins.model.lazy.LazyLoadRunMapEntrySet.size(LazyLoadRunMapEntrySet.java:42)
    	at java.base@17.0.13/java.util.AbstractMap.size(AbstractMap.java:85)
    	at java.base@17.0.13/java.util.Collections$UnmodifiableMap.size(Collections.java:1498)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.collectors.jobs.NbBuildsGauge.calculateMetric(NbBuildsGauge.java:33)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.collectors.jobs.NbBuildsGauge.calculateMetric(NbBuildsGauge.java:10)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.JobCollector.appendJobMetrics(JobCollector.java:231)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.JobCollector.lambda$collect$0(JobCollector.java:167)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.JobCollector$$Lambda$1184/0x00007fec84da47b0.accept(Unknown Source)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.util.Jobs.forEachJob(Jobs.java:19)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.JobCollector.collect(JobCollector.java:156)
    	at PluginClassLoader for prometheus//io.prometheus.client.Collector.collect(Collector.java:45)
    	at PluginClassLoader for prometheus//io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:204)
    	at PluginClassLoader for prometheus//io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:219)
    	at PluginClassLoader for prometheus//io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152)
    	at java.base@17.0.13/java.util.Enumeration$1.next(Enumeration.java:123)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.config.disabledmetrics.FilteredMetricEnumeration.filterList(FilteredMetricEnumeration.java:21)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.config.disabledmetrics.FilteredMetricEnumeration.<init>(FilteredMetricEnumeration.java:15)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.service.DefaultPrometheusMetrics.collectMetrics(DefaultPrometheusMetrics.java:101)
    	at PluginClassLoader for prometheus//org.jenkinsci.plugins.prometheus.service.PrometheusAsyncWorker.execute(PrometheusAsyncWorker.java:35)
    	at hudson.model.AsyncPeriodicWork.lambda$doRun$0(AsyncPeriodicWork.java:102)
    	at hudson.model.AsyncPeriodicWork$$Lambda$1112/0x00007fec84d5dc30.run(Unknown Source)
    	at java.base@17.0.13/java.lang.Thread.run(Thread.java:840)
```

### Anything else?

The thread dump seems to indicate the problem is in core but I am not familiar with any of this, creating the issue here because the plugin is mentioned in the stack trace

### Are you interested in contributing a fix?

Possibly, but I don't know where to start for this problem

**Comment by Waschndolos** [comment]
Thanks for the report. Could you provide a little more information so I might have a chance to reproduce?

Is it a pipeline job or a freestyle job? 
Does the job run on the controller node or on an agent node? 
Is it a long running job or a short one?
The job doesn't terminate?

**Comment by nattofriends** [comment]
> Thanks for the report. Could you provide a little more information so I might have a chance to reproduce?
> 
> Is it a pipeline job or a freestyle job?

Pipeline job triggered by Generic Webhook Plugin

>Does the job run on the controller node or on an agent node?

Agent nodes are used for the actual work (build and test)

>Is it a long running job or a short one? The job doesn't terminate?

Typically builds of this job finish in <1h. In this case, the build was not terminable by Timeout step, nor Script Console sinppets which call finish().

**Comment by tzhu-yelp** [comment]
> Thanks for the report. Could you provide a little more information so I might have a chance to reproduce?
> 
> Is it a pipeline job or a freestyle job?

Pipeline job triggered by Generic Webhook Plugin

>Does the job run on the controller node or on an agent node?

Agent nodes are used for the actual work (build and test)

>Is it a long running job or a short one? The job doesn't terminate?

Typically builds of this job finish in <1h. In this case, the build was not terminable by Timeout step, nor Script Console sinppets which call finish().

**Comment by tzhu-yelp** [comment]
I am still not sure how this problem is to be fixed in Core, but it looks like it could be avoided by calling `.getBuildsAsMap().getLoadedBuilds().size()` instead at https://github.com/jenkinsci/prometheus-plugin/blob/795.v995762102f28/src/main/java/org/jenkinsci/plugins/prometheus/collectors/jobs/NbBuildsGauge.java#L33, which does not load all the builds. Since this plugin is only interested in the count of builds, getting the size of a collection with possibly unloaded builds isn't a problem.

**Comment by Waschndolos** [comment]
Yeah that was also my first thought when I checked the code. I'll need to check the history why this was done this way but probably getting the size would be enough here

**Comment by Waschndolos** [comment]
ok now i know again :) The `hudson.model.Job` Object doesn't provide a method to get the list of build as a collection. It only provides an Iteratable. So the only option using a collection approach would be to use spliterator, or count the objects in the iterator which isn't quite perfomant on big jenkins agents I guess. I'll go with a lock approach which should fix the deadlock

**Comment by tzhu-yelp** [comment]
@Waschndolos: not sure how only locking in NbBuildsGauge can help with the stack trace in the first deadlocked thread: 

```
    "Executor #-1 for Built-In Node" Id=138915 Group=main BLOCKED on jenkins.model.lazy.LazyLoadRunMapEntrySet@1bcc66c7 owned by "prometheus_async_worker thread" Id=138789
    	at jenkins.model.lazy.LazyLoadRunMapEntrySet.clearCache(LazyLoadRunMapEntrySet.java:37)
    	-  blocked on jenkins.model.lazy.LazyLoadRunMapEntrySet@1bcc66c7
    	at jenkins.model.lazy.AbstractLazyLoadRunMap.put(AbstractLazyLoadRunMap.java:625)
    	-  locked hudson.model.RunMap@3f263d52
    	at jenkins.model.lazy.AbstractLazyLoadRunMap._put(AbstractLazyLoadRunMap.java:606)
    	at hudson.model.RunMap.put(RunMap.java:227)
    	at jenkins.model.lazy.LazyBuildMixIn.newBuild(LazyBuildMixIn.java:192)
    	-  locked org.jenkinsci.plugins.workflow.job.WorkflowJob$1@149939d4
    	at jenkins.model.ParameterizedJobMixIn$ParameterizedJob.createExecutable(ParameterizedJobMixIn.java:507)
    	at jenkins.model.ParameterizedJobMixIn$ParameterizedJob.createExecutable(ParameterizedJobMixIn.java:325)
    	at hudson.model.Executor$1.call(Executor.java:374)
    	at hudson.model.Executor$1.call(Executor.java:354)
    	at hudson.model.Queue._withLock(Queue.java:1470)
    	at hudson.model.Queue.withLock(Queue.java:1326)
    	at hudson.model.Executor.run(Executor.java:354)
    
    	Number of locked synchronizers = 1
    	- java.util.concurrent.locks.ReentrantLock$NonfairSync@323aed2d
```

**Comment by Waschndolos** [comment]
I can only adjust code in that plugin. I would expect that it helps. Do you have another solution?

**Comment by Waschndolos** [comment]
@tzhu-yelp should I release and you try it?

**Comment by Waschndolos** [comment]
Release is on the way - Please check if that helps, if not we re-check. It's my day off today so I'll turn off the computer ;)

**Comment by tzhu-yelp** [comment]
Thanks, I will try the new version.

**Comment by tzhu-yelp** [comment]
I think this would be avoided with something like
```diff
diff --git a/src/main/java/org/jenkinsci/plugins/prometheus/collectors/jobs/NbBuildsGauge.java b/src/main/java/org/jenkinsci/plugins/prometheus/collectors/jobs/NbBuildsGauge.java
index fcfae1c..e76b509 100644
--- a/src/main/java/org/jenkinsci/plugins/prometheus/collectors/jobs/NbBuildsGauge.java
+++ b/src/main/java/org/jenkinsci/plugins/prometheus/collectors/jobs/NbBuildsGauge.java
@@ -1,11 +1,14 @@
 package org.jenkinsci.plugins.prometheus.collectors.jobs;

 import hudson.model.Job;
+import hudson.model.RunMap;
 import io.prometheus.client.Gauge;
 import io.prometheus.client.SimpleCollector;
 import org.jenkinsci.plugins.prometheus.collectors.CollectorType;
 import org.jenkinsci.plugins.prometheus.collectors.builds.BuildsMetricCollector;

+import java.util.SortedMap;
+

 public class NbBuildsGauge extends BuildsMetricCollector<Job<?, ?>, Gauge> {

@@ -30,7 +33,14 @@ public class NbBuildsGauge extends BuildsMetricCollector<Job<?, ?>, Gauge> {

     @Override
     public void calculateMetric(Job<?, ?> jenkinsObject, String[] labelValues) {
-        int nbBuilds = jenkinsObject.getBuildsAsMap().size();
+        SortedMap<?, ?> builds = jenkinsObject.getBuildsAsMap();
+        int nbBuilds;
+        if (builds instanceof RunMap<?>) {
+            // No need to eagerly load builds just to get the size
+            nbBuilds = ((RunMap<?>) builds).getLoadedBuilds().size();
+        } else {
+            nbBuilds = builds.size();
+        }
         this.collector.labels(labelValues).set(nbBuilds);
     }
 }
```

I am also testing the version you released recently.
